services:
  postgres:
    container_name: diario
    hostname: diario
    image: postgres
    restart: always
    volumes:
      - ./local/path:/container/path
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: diario
    ports:
      - 5432:5432